server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: milodola
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
